### PR TITLE
Omnibus fixes

### PR DESCRIPTION
**Pull request by erikh**
This includes the commits from my previous pull request related to the UI and AMQP issues.

The fixes specific to this request:
- communicate to the user when the package can't be downloaded (right now it just bails silently)
- fix a spelling error
- provide a --no-test/-n option which does not run opscode pedant after installing erchef. This speeds up install time significantly if you're not interested in the test results.

### CODE REVIEW

**Comment by fnichol** [comment]
Looking good!

**Comment by erikh** [comment]
Thanks -- actually sorting an issue here with platform selection and chef
10, and another with SSL on chef 10 -- i'll probably have another PR in an
hour or two as a result of that, need to get my ducks in a row first.

**Comment by fnichol** [comment]
Sure thing, I'll hold off for the moment on a gem release then, may as well bundle it all up.

**Comment by erikh** [comment]
@fnichol 

so the SSL bit is a bit involved and won't affect most consumers -- basically, knife uses Net::HTTP which by default attempts a SSLv23 (SSLv2 and SSLv3) negotiation -- the apache install on debian at least rejects SSLv2 at the openssl package level -- not configurable, which Net::HTTP doesn't gracefully handle. Net::HTTP allows you to change this, but this isn't exposed to knife users. I'm not sure there's a straightforward way to deal with this and I'd rather not hold up a bunch of bug fixes over it.

I'll get you a solution to this (I need it for chef-workflow), but it may not come in patch form, just a "hey, users, if you have this problem etc etc" thing.

I guess what I'm saying is you can probably kick out a release and I'd be really surprised if I came back two days later asking you to do it again.

As always, thanks for the awesome facilitation and project.

**Comment by erikh** [comment]
it's not pretty, but here's the fix for this issue, should you have any trouble with users, or want to add it to the documentation: https://gist.github.com/erikh/5239560

And yes, that is a monkeypatch to Net::HTTP in a knife.rb :)

**Comment by erikh** [comment]
relevant opscode ticket: https://tickets.opscode.com/browse/CHEF-4033

**Comment by erikh** [comment]
fwiw, while severely lacking in docs, and waiting on the release of these patches (the Gemfile works though), here's what I've been using to test all this stuff: https://github.com/chef-workflow/furnish-knife-server

**Pull request merged**
