### PR TITLE
add chef-server-redhat template

### PR DESCRIPTION
**Pull request by danryan**
Initial stab at a RHEL variant of the chef-server bootstrap template. I've only tested on CentOS (and thusly this only supports CentOS). 

Items of note:
- This installs chef-server via gems as RPMs currently lag behind their Debian counterparts. \* \* The `chef-server` cookbook in its released form doesn't provide a way to set webui attributes so the webui is not completely configured.

### CODE REVIEW

**Comment by danryan** [comment]
Hmm, I neglected to include a method of installing ruby or rubygems. Please disregard this PR until I amend that oversight.

**Comment by danryan** [comment]
Ok, this pull request is now ready for review :)

**Comment by fnichol** [comment]
This looks great! I've been wanting the option to run on a rhel-based distro. I take it a user would just set their platform flag (`--platform rehat`) and they're off?

I'll give this a shot today and confirm if it works on scientific-6.

**Comment by danryan** [comment]
@fnichol Correct, `--platform redhat` is what I am using to choose this template over the Debian one. There might be an issue with SL around setting hostnames as it'll just exec for CentOS at the moment. I'll see if I can fix it.

**Comment by danryan** [comment]
A few more changes:
- Renamed the template to `chef-server-rhel` to correctly match Chef's `platform_family` designation
- Added detection for different clone variants (Boy, do I take ohai for granted! :smile:)
- Added functions for each of the platforms supported under the RHEL family.

**Comment by erikh** [comment]
Q: would there be any value in a --platform auto which figured out what kind of host and went from there?

I can add that independently of this, just wondering what you guys think.

**Comment by danryan** [comment]
@erikh How would that work? Would it assume the OS of the provisioning machine? I wouldn't find any benefit from it personally because I often bootstrap from a different OS (OS X -> Ubuntu/CentOS, etc.), though I could certainly see the use case for others.

**Comment by erikh** [comment]
nah. I was thinking it'd shell in, check something ala `lsb-release` to determine the host, then perform the bootstrap like the proper `--platform` argument was passed.

it'd be really nice for chef-workflow, because then I could focus on the machines being provisioned, not which platform to support. obviously though, it's a bit more work.

**Comment by erikh** [comment]
stop the presses; found a few ugly bugs with this. I have some patches coming, but they'll be a part of a larger PR. Hope to get them here later tonight. Just thought I'd mention it.

**Comment by danryan** [comment]
Closing in favor of #22

**Pull request closed without merging**
